# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AboutWin(object):
    def setupUi(self, about_dialog):
        about_dialog.setObjectName("about_dialog")
        about_dialog.resize(450, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(about_dialog.sizePolicy().hasHeightForWidth())
        about_dialog.setSizePolicy(sizePolicy)
        about_dialog.setMinimumSize(QtCore.QSize(450, 230))
        about_dialog.setMaximumSize(QtCore.QSize(450, 230))
        self.gridLayout = QtWidgets.QGridLayout(about_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.date = QtWidgets.QLabel(about_dialog)
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 3, 1, 1, 1)
        self.vers = QtWidgets.QLabel(about_dialog)
        self.vers.setObjectName("vers")
        self.gridLayout.addWidget(self.vers, 1, 1, 1, 1)
        self.ok_btn = QtWidgets.QPushButton(about_dialog)
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout.addWidget(self.ok_btn, 0, 2, 1, 1)
        self.pict = QtWidgets.QLabel(about_dialog)
        self.pict.setText("")
        self.pict.setPixmap(QtGui.QPixmap("icon.ico"))
        self.pict.setObjectName("pict")
        self.gridLayout.addWidget(self.pict, 0, 1, 1, 1)
        self.oth = QtWidgets.QLabel(about_dialog)
        self.oth.setObjectName("oth")
        self.gridLayout.addWidget(self.oth, 2, 1, 1, 1)

        self.retranslateUi(about_dialog)
        QtCore.QMetaObject.connectSlotsByName(about_dialog)

    def retranslateUi(self, about_dialog):
        _translate = QtCore.QCoreApplication.translate
        about_dialog.setWindowTitle(_translate("about_dialog", "About MODBUSSER"))
        self.date.setText(_translate("about_dialog", "(c) Yuri Sh"))
        self.vers.setText(_translate("about_dialog", "MODBUSSER. Version 1.1.0"))
        self.ok_btn.setText(_translate("about_dialog", "Ок"))
        self.oth.setText(_translate("about_dialog", "Special for APS ENERGIA RUS Ltd."))
